/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author omsay9559
 */
public class MakingAPurchaseGUI extends javax.swing.JFrame {

    /**
     * Creates new form MakingAPurchaseGUI
     */
    public MakingAPurchaseGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        glazedlbl = new javax.swing.JLabel();
        glazedNum = new javax.swing.JTextField();
        chocoLbl = new javax.swing.JLabel();
        chocoNum = new javax.swing.JTextField();
        bostonLbl = new javax.swing.JLabel();
        bostonNum = new javax.swing.JTextField();
        honeyLbl = new javax.swing.JLabel();
        honeyNum = new javax.swing.JTextField();
        sprinkleLbl = new javax.swing.JLabel();
        sprinkleNum = new javax.swing.JTextField();
        tabulateBtn = new javax.swing.JButton();
        subtotalLbl = new javax.swing.JLabel();
        hstLbl = new javax.swing.JLabel();
        GrandTotalLbl = new javax.swing.JLabel();
        subtotalNum = new javax.swing.JLabel();
        hstNum = new javax.swing.JLabel();
        grandTotalNum = new javax.swing.JLabel();
        instructionsLbl = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Broadway", 3, 21)); // NOI18N
        jLabel1.setText("Omar's Cupcakes");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 102));

        titleLbl.setFont(new java.awt.Font("Broadway", 3, 22)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 0, 255));
        titleLbl.setText("Omar's Donuts");

        glazedlbl.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        glazedlbl.setText("Classic Glazed ($0.99):");

        glazedNum.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        glazedNum.setText("0");
        glazedNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                glazedNumActionPerformed(evt);
            }
        });

        chocoLbl.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        chocoLbl.setText("Chocolate Dipped ($0.99):");

        chocoNum.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        chocoNum.setText("0");
        chocoNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chocoNumActionPerformed(evt);
            }
        });

        bostonLbl.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        bostonLbl.setText("Boston Cream ($1.39):");

        bostonNum.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        bostonNum.setText("0");
        bostonNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bostonNumActionPerformed(evt);
            }
        });

        honeyLbl.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        honeyLbl.setText("Honey Cruller ($1.39):");

        honeyNum.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        honeyNum.setText("0");
        honeyNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                honeyNumActionPerformed(evt);
            }
        });

        sprinkleLbl.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        sprinkleLbl.setText("Sprinkle Dipped ($1.19):");

        sprinkleNum.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        sprinkleNum.setText("0");
        sprinkleNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sprinkleNumActionPerformed(evt);
            }
        });

        tabulateBtn.setText("Tabulate");
        tabulateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabulateBtnActionPerformed(evt);
            }
        });

        subtotalLbl.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        subtotalLbl.setText("Subtotal:");

        hstLbl.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        hstLbl.setText("HST (13%):");

        GrandTotalLbl.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        GrandTotalLbl.setText(" Grand Total:");

        subtotalNum.setText("$0.00");

        hstNum.setText("$0.00");

        grandTotalNum.setText("$0.00");

        instructionsLbl.setFont(new java.awt.Font("Broadway", 0, 14)); // NOI18N
        instructionsLbl.setForeground(new java.awt.Color(0, 0, 153));
        instructionsLbl.setText("Enter the number of donuts you would like & hit Tabulate ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(instructionsLbl)
                .addGap(0, 22, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chocoLbl)
                            .addComponent(glazedlbl)
                            .addComponent(bostonLbl)
                            .addComponent(honeyLbl)
                            .addComponent(sprinkleLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(glazedNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(tabulateBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(honeyNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GrandTotalLbl)
                                .addGap(18, 18, 18)
                                .addComponent(grandTotalNum))
                            .addComponent(sprinkleNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bostonNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(hstLbl))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(chocoNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(subtotalLbl)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subtotalNum)
                                    .addComponent(hstNum)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(titleLbl)
                .addGap(18, 18, 18)
                .addComponent(instructionsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(glazedNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tabulateBtn))
                    .addComponent(glazedlbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chocoNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chocoLbl)
                    .addComponent(subtotalLbl)
                    .addComponent(subtotalNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bostonNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bostonLbl)
                    .addComponent(hstLbl)
                    .addComponent(hstNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(honeyLbl)
                    .addComponent(honeyNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GrandTotalLbl)
                    .addComponent(grandTotalNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sprinkleLbl)
                    .addComponent(sprinkleNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void glazedNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_glazedNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_glazedNumActionPerformed

    private void chocoNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chocoNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chocoNumActionPerformed

    private void bostonNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bostonNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bostonNumActionPerformed

    private void honeyNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_honeyNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_honeyNumActionPerformed

    private void sprinkleNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sprinkleNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sprinkleNumActionPerformed

    private void tabulateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabulateBtnActionPerformed
        //declare variables
        double bostonPrc, chocoPrc, glazedPrc, honeyPrc, sprinklePrc, subTotal, HST, grandTotal;
        
        final double TAX = 0.13;
        final double BOSTON = 1.39;
        final double CHOCO = 0.99;
        final double GLAZED = 0.99;
        final double HONEY = 1.39;
        final double SPRINKLE = 1.19;
        
//        bostonPrc = (int) (Integer.parseInt(bostonNum.getText())* BOSTON);
//        chocoPrc = (int) (Integer.parseInt(chocoNum.getText())* CHOCO);
//        glazedPrc = (int) (Integer.parseInt(glazedNum.getText())* GLAZED);
//        honeyPrc = (int) (Integer.parseInt(honeyNum.getText())* HONEY);
//        sprinklePrc = (int) (Integer.parseInt(sprinkleNum.getText())* SPRINKLE);
        //grab user's input
        bostonPrc = (Double.parseDouble(bostonNum.getText())* BOSTON);
        chocoPrc =  (Double.parseDouble(chocoNum.getText())* CHOCO);
        glazedPrc = (Double.parseDouble(glazedNum.getText())* GLAZED);
        honeyPrc =  (Double.parseDouble(honeyNum.getText())* HONEY);
        sprinklePrc =  (Double.parseDouble(sprinkleNum.getText())* SPRINKLE);
        
        //calculate totals
        subTotal= glazedPrc + bostonPrc + chocoPrc + honeyPrc + sprinklePrc;
        HST=  (subTotal * TAX );
        grandTotal = subTotal + HST;
        //output totals
            subTotal = subTotal * 100;
            subTotal = Math.round (subTotal);
            subTotal = subTotal / 100;
            
            HST = HST * 100;
            HST = Math.round (HST);
            HST = HST / 100;
            
            grandTotal = grandTotal * 100;
            grandTotal = Math.round (grandTotal);
            grandTotal = grandTotal / 100;
            
        subtotalNum.setText ("$" + subTotal);
        hstNum.setText ("$" + HST);
        grandTotalNum.setText ("$" + grandTotal);
                
    }//GEN-LAST:event_tabulateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakingAPurchaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakingAPurchaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakingAPurchaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakingAPurchaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MakingAPurchaseGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GrandTotalLbl;
    private javax.swing.JLabel bostonLbl;
    private javax.swing.JTextField bostonNum;
    private javax.swing.JLabel chocoLbl;
    private javax.swing.JTextField chocoNum;
    private javax.swing.JTextField glazedNum;
    private javax.swing.JLabel glazedlbl;
    private javax.swing.JLabel grandTotalNum;
    private javax.swing.JLabel honeyLbl;
    private javax.swing.JTextField honeyNum;
    private javax.swing.JLabel hstLbl;
    private javax.swing.JLabel hstNum;
    private javax.swing.JLabel instructionsLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel sprinkleLbl;
    private javax.swing.JTextField sprinkleNum;
    private javax.swing.JLabel subtotalLbl;
    private javax.swing.JLabel subtotalNum;
    private javax.swing.JButton tabulateBtn;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
