/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author omsay9559
 */
public class diceGuessingGame extends javax.swing.JFrame {
//declare variables
int totalRolls = 0;
int totalCorrect = 0;
int totalIncorrect = 0;
int userGuess = 0;
int diceRoll = 0;
double percCorrect = 0;


    /**
     * Creates new form diceGuessingGame
     */
    public diceGuessingGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        instructionLbl = new javax.swing.JLabel();
        guessLbl = new javax.swing.JLabel();
        inputGuessNum = new javax.swing.JTextField();
        rollBtn = new javax.swing.JButton();
        outcomeLbl = new javax.swing.JLabel();
        outcomeNumLbl = new javax.swing.JLabel();
        rollCountLbl = new javax.swing.JLabel();
        rollCountNum = new javax.swing.JLabel();
        correctGuessCountLbl = new javax.swing.JLabel();
        CorrectGuessNumCounter = new javax.swing.JLabel();
        incorrectCountLbl = new javax.swing.JLabel();
        incorrectGuessCountNum = new javax.swing.JLabel();
        perCorrectLbl = new javax.swing.JLabel();
        perCorrectNum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Rockwell", 0, 21)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(102, 0, 153));
        titleLbl.setText("The Awesome Dice Guessing game");

        instructionLbl.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        instructionLbl.setForeground(new java.awt.Color(102, 0, 153));
        instructionLbl.setText("Enter a number, from 1 to 6 and click roll dice");

        guessLbl.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        guessLbl.setForeground(new java.awt.Color(102, 0, 153));
        guessLbl.setText("Your Guess");

        inputGuessNum.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        inputGuessNum.setForeground(new java.awt.Color(102, 0, 153));
        inputGuessNum.setText("0");
        inputGuessNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputGuessNumActionPerformed(evt);
            }
        });

        rollBtn.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        rollBtn.setForeground(new java.awt.Color(102, 0, 153));
        rollBtn.setText("Roll Dice");
        rollBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollBtnActionPerformed(evt);
            }
        });

        outcomeLbl.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        outcomeLbl.setForeground(new java.awt.Color(102, 0, 153));
        outcomeLbl.setText("Dice Roll");

        outcomeNumLbl.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        outcomeNumLbl.setForeground(new java.awt.Color(102, 0, 153));
        outcomeNumLbl.setText("0");

        rollCountLbl.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        rollCountLbl.setForeground(new java.awt.Color(102, 0, 153));
        rollCountLbl.setText("Number of Rolls:");

        rollCountNum.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        rollCountNum.setForeground(new java.awt.Color(102, 0, 153));
        rollCountNum.setText("0");

        correctGuessCountLbl.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        correctGuessCountLbl.setForeground(new java.awt.Color(102, 0, 153));
        correctGuessCountLbl.setText("Number of Correct Guesses:");

        CorrectGuessNumCounter.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        CorrectGuessNumCounter.setForeground(new java.awt.Color(102, 0, 153));
        CorrectGuessNumCounter.setText("0");

        incorrectCountLbl.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        incorrectCountLbl.setForeground(new java.awt.Color(102, 0, 153));
        incorrectCountLbl.setText("Number of incorrect Guesses:");

        incorrectGuessCountNum.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        incorrectGuessCountNum.setForeground(new java.awt.Color(102, 0, 153));
        incorrectGuessCountNum.setText("0");

        perCorrectLbl.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        perCorrectLbl.setForeground(new java.awt.Color(102, 0, 153));
        perCorrectLbl.setText("Percentage of Correct Guesses:");

        perCorrectNum.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        perCorrectNum.setForeground(new java.awt.Color(102, 0, 153));
        perCorrectNum.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(titleLbl)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(instructionLbl)
                        .addGap(87, 87, 87))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(guessLbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(inputGuessNum, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rollBtn)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rollCountLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(correctGuessCountLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(incorrectCountLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(perCorrectLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(22, 22, 22)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(outcomeLbl)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rollCountNum)
                            .addComponent(outcomeNumLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CorrectGuessNumCounter)
                            .addComponent(incorrectGuessCountNum)
                            .addComponent(perCorrectNum))
                        .addGap(74, 74, 74))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(titleLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(instructionLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guessLbl)
                            .addComponent(outcomeLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outcomeNumLbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputGuessNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rollBtn))))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rollCountLbl)
                    .addComponent(rollCountNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correctGuessCountLbl)
                    .addComponent(CorrectGuessNumCounter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(incorrectGuessCountNum)
                    .addComponent(incorrectCountLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(perCorrectNum)
                    .addComponent(perCorrectLbl))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputGuessNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputGuessNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputGuessNumActionPerformed

    private void rollBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollBtnActionPerformed
        diceRoll = (int)Math.round(Math.random()*5+1);
        outcomeNumLbl.setText(String.valueOf(diceRoll));
        
        userGuess = Integer.parseInt(inputGuessNum.getText());
       
        totalRolls = totalRolls + 1;
        
        if (diceRoll== userGuess)
        {
            totalCorrect = totalCorrect + 1;
        }
        else 
        {
            totalIncorrect = totalIncorrect + 1;
        }
        
        percCorrect = ((double) totalCorrect/(double)totalRolls)*100;
        
         
            percCorrect = percCorrect * 100;
            percCorrect = Math.round (percCorrect);
            percCorrect = percCorrect / 100;
            
            rollCountNum.setText(String.valueOf(totalRolls));
            CorrectGuessNumCounter.setText(String.valueOf(totalCorrect));
            incorrectGuessCountNum.setText(String.valueOf(totalIncorrect));
            perCorrectNum.setText("%" + String.valueOf(percCorrect));
    }//GEN-LAST:event_rollBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diceGuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diceGuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diceGuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diceGuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new diceGuessingGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CorrectGuessNumCounter;
    private javax.swing.JLabel correctGuessCountLbl;
    private javax.swing.JLabel guessLbl;
    private javax.swing.JLabel incorrectCountLbl;
    private javax.swing.JLabel incorrectGuessCountNum;
    private javax.swing.JTextField inputGuessNum;
    private javax.swing.JLabel instructionLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel outcomeLbl;
    private javax.swing.JLabel outcomeNumLbl;
    private javax.swing.JLabel perCorrectLbl;
    private javax.swing.JLabel perCorrectNum;
    private javax.swing.JButton rollBtn;
    private javax.swing.JLabel rollCountLbl;
    private javax.swing.JLabel rollCountNum;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
