/*
 Omar Sayyed
October 11th 2018
Calculates the cost of a pizza and outputs a messege based on the diamater 
 */

/**
 *
 * @author omsay9559
 */
public class pizzaProject extends javax.swing.JFrame {

    /**
     * Creates new form pizzaProject
     */
    public pizzaProject() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        diamaterLbl = new javax.swing.JLabel();
        diamaterNum = new javax.swing.JTextField();
        tabBtn = new javax.swing.JButton();
        subtotalLbl = new javax.swing.JLabel();
        subtotalNum = new javax.swing.JLabel();
        taxLbl = new javax.swing.JLabel();
        taxNum = new javax.swing.JLabel();
        grandTotalLbl = new javax.swing.JLabel();
        grandTotalNum = new javax.swing.JLabel();
        outputMessegeLbl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        titleLbl.setFont(new java.awt.Font("Lucida Handwriting", 3, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(204, 0, 0));
        titleLbl.setText("Welcome  to  Omar's Pizzeria ");

        diamaterLbl.setFont(new java.awt.Font("Elephant", 0, 11)); // NOI18N
        diamaterLbl.setForeground(new java.awt.Color(204, 0, 0));
        diamaterLbl.setText("Enter the diamater (cm) of the pizza you would like:");

        diamaterNum.setBackground(new java.awt.Color(255, 204, 0));
        diamaterNum.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        diamaterNum.setForeground(new java.awt.Color(204, 0, 0));
        diamaterNum.setText("0");
        diamaterNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diamaterNumActionPerformed(evt);
            }
        });

        tabBtn.setFont(new java.awt.Font("Elephant", 0, 11)); // NOI18N
        tabBtn.setForeground(new java.awt.Color(204, 0, 0));
        tabBtn.setText("Tabulate");
        tabBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabBtnActionPerformed(evt);
            }
        });

        subtotalLbl.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        subtotalLbl.setForeground(new java.awt.Color(204, 0, 0));
        subtotalLbl.setText("Subtotal:  $");

        subtotalNum.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        subtotalNum.setForeground(new java.awt.Color(204, 0, 0));
        subtotalNum.setText("0.00");

        taxLbl.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        taxLbl.setForeground(new java.awt.Color(204, 0, 0));
        taxLbl.setText("Taxes:      $");

        taxNum.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        taxNum.setForeground(new java.awt.Color(204, 0, 0));
        taxNum.setText("0.00");

        grandTotalLbl.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        grandTotalLbl.setForeground(new java.awt.Color(204, 0, 0));
        grandTotalLbl.setText("0.00");

        grandTotalNum.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        grandTotalNum.setForeground(new java.awt.Color(204, 0, 0));
        grandTotalNum.setText("Grand Total:      $");

        outputMessegeLbl.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        outputMessegeLbl.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tabBtn)
                .addGap(169, 169, 169))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(titleLbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(diamaterLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(diamaterNum, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(taxLbl)
                            .addComponent(grandTotalNum)
                            .addComponent(subtotalLbl))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taxNum)
                            .addComponent(subtotalNum)
                            .addComponent(grandTotalLbl))))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outputMessegeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diamaterLbl)
                    .addComponent(diamaterNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtotalLbl)
                    .addComponent(subtotalNum))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taxNum)
                    .addComponent(taxLbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grandTotalNum)
                    .addComponent(grandTotalLbl))
                .addGap(25, 25, 25)
                .addComponent(outputMessegeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        File.setText("File");
        jMenuBar1.add(File);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diamaterNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diamaterNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diamaterNumActionPerformed

    private void tabBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabBtnActionPerformed
        //declare variables
        double subtotal, tax, grandTotal;
        double diamater;
        final double HST = 0.13;
        final double INITIAL_COST = 1.74;
        final double COST_PER_CM = 0.50;
        diamater = (Double.parseDouble(diamaterNum.getText()));
        
        //calculate subtotal, tax and grand total
            subtotal = INITIAL_COST + (COST_PER_CM * diamater);
            tax = subtotal*HST;
            grandTotal = tax + subtotal;
            
              //rounding 
            grandTotal = grandTotal * 100;
            grandTotal = Math.round (grandTotal);
            grandTotal = grandTotal / 100;
            
            tax = tax * 100;
            tax = Math.round (tax);
            tax = tax / 100;
            
            //output costs
             subtotalNum.setText ("" + subtotal );
             taxNum.setText ("" + tax );
             grandTotalLbl.setText ("" + grandTotal );
           
             //output message depending on diamater of pizza
                if (diamater < 15 ){
                    outputMessegeLbl.setText ("We are going to make you a cute little pizza!");
                }
                else if (diamater < 20 ){
                    outputMessegeLbl.setText ("you like weird sizes!");
                }
                else if (diamater < 40){
                    outputMessegeLbl.setText ("This will be delicious!");
                }
                else {
                    outputMessegeLbl.setText ("Whoa, big pizza! You might need a truck to get this home!");
                }   
    }//GEN-LAST:event_tabBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pizzaProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pizzaProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pizzaProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pizzaProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new pizzaProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu File;
    private javax.swing.JLabel diamaterLbl;
    private javax.swing.JTextField diamaterNum;
    private javax.swing.JLabel grandTotalLbl;
    private javax.swing.JLabel grandTotalNum;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel outputMessegeLbl;
    private javax.swing.JLabel subtotalLbl;
    private javax.swing.JLabel subtotalNum;
    private javax.swing.JButton tabBtn;
    private javax.swing.JLabel taxLbl;
    private javax.swing.JLabel taxNum;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
