/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author omsay9559
 */
public class MultipleChoiceQuiz extends javax.swing.JFrame {

    /**
     * Creates new form MultipleChoiceQuiz
     */
    public MultipleChoiceQuiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        questionLbl0 = new javax.swing.JLabel();
        ansALbl0 = new javax.swing.JLabel();
        ansBLbl0 = new javax.swing.JLabel();
        ansCLbl0 = new javax.swing.JLabel();
        ansDLbl0 = new javax.swing.JLabel();
        userAnswer0 = new javax.swing.JTextField();
        answerPromptLbl0 = new javax.swing.JLabel();
        numCorrectLbl = new javax.swing.JLabel();
        numCorrectNum = new javax.swing.JLabel();
        numIncorrectLbl = new javax.swing.JLabel();
        numIncorrectNum = new javax.swing.JLabel();
        perCorrectLbl = new javax.swing.JLabel();
        perCorrectNum = new javax.swing.JLabel();
        ansALbl1 = new javax.swing.JLabel();
        answerPromptLbl1 = new javax.swing.JLabel();
        ansBLbl1 = new javax.swing.JLabel();
        ansCLbl1 = new javax.swing.JLabel();
        userAnswer1 = new javax.swing.JTextField();
        ansDLbl1 = new javax.swing.JLabel();
        questionLbl1 = new javax.swing.JLabel();
        questionLbl2 = new javax.swing.JLabel();
        ansALbl2 = new javax.swing.JLabel();
        ansBLbl2 = new javax.swing.JLabel();
        ansCLbl2 = new javax.swing.JLabel();
        ansDLbl2 = new javax.swing.JLabel();
        answerPromptLbl2 = new javax.swing.JLabel();
        userAnswer2 = new javax.swing.JTextField();
        questionLbl3 = new javax.swing.JLabel();
        ansALbl3 = new javax.swing.JLabel();
        ansBLbl3 = new javax.swing.JLabel();
        ansCLbl3 = new javax.swing.JLabel();
        ansDLbl3 = new javax.swing.JLabel();
        answerPromptLbl3 = new javax.swing.JLabel();
        userAnswer3 = new javax.swing.JTextField();
        questionLbl4 = new javax.swing.JLabel();
        ansALbl4 = new javax.swing.JLabel();
        ansBLbl4 = new javax.swing.JLabel();
        ansCLbl4 = new javax.swing.JLabel();
        ansDLbl4 = new javax.swing.JLabel();
        answerPromptLbl4 = new javax.swing.JLabel();
        userAnswer4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setForeground(new java.awt.Color(0, 51, 255));

        questionLbl0.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        questionLbl0.setForeground(new java.awt.Color(204, 0, 0));
        questionLbl0.setText("Where was Basketball Created?");

        ansALbl0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ansALbl0.setForeground(new java.awt.Color(204, 0, 0));
        ansALbl0.setText("A) America");

        ansBLbl0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ansBLbl0.setForeground(new java.awt.Color(204, 0, 0));
        ansBLbl0.setText("B) England");

        ansCLbl0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ansCLbl0.setForeground(new java.awt.Color(204, 0, 0));
        ansCLbl0.setText("C) Canada");

        ansDLbl0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ansDLbl0.setForeground(new java.awt.Color(204, 0, 0));
        ansDLbl0.setText("D) Africa");

        userAnswer0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userAnswer0ActionPerformed(evt);
            }
        });

        answerPromptLbl0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        answerPromptLbl0.setForeground(new java.awt.Color(204, 0, 0));
        answerPromptLbl0.setText("Enter Your answer here:");

        numCorrectLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numCorrectLbl.setForeground(new java.awt.Color(204, 0, 0));
        numCorrectLbl.setText("Number Correct:");

        numCorrectNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numCorrectNum.setForeground(new java.awt.Color(204, 0, 0));
        numCorrectNum.setText("0");

        numIncorrectLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numIncorrectLbl.setForeground(new java.awt.Color(204, 0, 0));
        numIncorrectLbl.setText("Number Incorrect:");

        numIncorrectNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numIncorrectNum.setForeground(new java.awt.Color(204, 0, 0));
        numIncorrectNum.setText("0");

        perCorrectLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        perCorrectLbl.setForeground(new java.awt.Color(204, 0, 0));
        perCorrectLbl.setText("Percentage Correct:");

        perCorrectNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        perCorrectNum.setForeground(new java.awt.Color(204, 0, 0));
        perCorrectNum.setText("0");

        ansALbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ansALbl1.setForeground(new java.awt.Color(204, 0, 0));
        ansALbl1.setText("A) San Francisco");

        answerPromptLbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        answerPromptLbl1.setForeground(new java.awt.Color(204, 0, 0));
        answerPromptLbl1.setText("Enter Your answer here:");

        ansBLbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ansBLbl1.setForeground(new java.awt.Color(204, 0, 0));
        ansBLbl1.setText("B) Toronto");

        ansCLbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ansCLbl1.setForeground(new java.awt.Color(204, 0, 0));
        ansCLbl1.setText("C) New York");

        userAnswer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userAnswer1ActionPerformed(evt);
            }
        });

        ansDLbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ansDLbl1.setForeground(new java.awt.Color(204, 0, 0));
        ansDLbl1.setText("D) Tokyo");

        questionLbl1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        questionLbl1.setForeground(new java.awt.Color(204, 0, 0));
        questionLbl1.setText("Where is Silicon Valley?");

        questionLbl2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        questionLbl2.setForeground(new java.awt.Color(204, 0, 0));
        questionLbl2.setText("Which company is not based in Silicon Valley?");

        ansALbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ansALbl2.setForeground(new java.awt.Color(204, 0, 0));
        ansALbl2.setText("A) Apple");

        ansBLbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ansBLbl2.setForeground(new java.awt.Color(204, 0, 0));
        ansBLbl2.setText("B) Amazon");

        ansCLbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ansCLbl2.setForeground(new java.awt.Color(204, 0, 0));
        ansCLbl2.setText("C) Google");

        ansDLbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ansDLbl2.setForeground(new java.awt.Color(204, 0, 0));
        ansDLbl2.setText("D) Microsoft");

        answerPromptLbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        answerPromptLbl2.setForeground(new java.awt.Color(204, 0, 0));
        answerPromptLbl2.setText("Enter Your answer here:");

        userAnswer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userAnswer2ActionPerformed(evt);
            }
        });

        questionLbl3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        questionLbl3.setForeground(new java.awt.Color(204, 0, 0));
        questionLbl3.setText("Which city is considired China's Silicon Valley?");

        ansALbl3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ansALbl3.setForeground(new java.awt.Color(204, 0, 0));
        ansALbl3.setText("A) Shanghai ");

        ansBLbl3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ansBLbl3.setForeground(new java.awt.Color(204, 0, 0));
        ansBLbl3.setText("B) Beijing");

        ansCLbl3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ansCLbl3.setForeground(new java.awt.Color(204, 0, 0));
        ansCLbl3.setText("C) Hong Kong");

        ansDLbl3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ansDLbl3.setForeground(new java.awt.Color(204, 0, 0));
        ansDLbl3.setText("D) Shenzen");

        answerPromptLbl3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        answerPromptLbl3.setForeground(new java.awt.Color(204, 0, 0));
        answerPromptLbl3.setText("Enter Your answer here:");

        userAnswer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userAnswer3ActionPerformed(evt);
            }
        });

        questionLbl4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        questionLbl4.setForeground(new java.awt.Color(204, 0, 0));
        questionLbl4.setText("Which one of the following is Silicon's symbol on the periodic table?");

        ansALbl4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ansALbl4.setForeground(new java.awt.Color(204, 0, 0));
        ansALbl4.setText("A) Sl");

        ansBLbl4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ansBLbl4.setForeground(new java.awt.Color(204, 0, 0));
        ansBLbl4.setText("B) Si");

        ansCLbl4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ansCLbl4.setForeground(new java.awt.Color(204, 0, 0));
        ansCLbl4.setText("C) S");

        ansDLbl4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ansDLbl4.setForeground(new java.awt.Color(204, 0, 0));
        ansDLbl4.setText("D) Sc");

        answerPromptLbl4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        answerPromptLbl4.setForeground(new java.awt.Color(204, 0, 0));
        answerPromptLbl4.setText("Enter Your answer here:");

        userAnswer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userAnswer4ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Calculate Score");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(answerPromptLbl0)
                                .addGap(18, 18, 18)
                                .addComponent(userAnswer0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ansALbl0)
                                .addGap(18, 18, 18)
                                .addComponent(ansBLbl0)
                                .addGap(18, 18, 18)
                                .addComponent(ansCLbl0)
                                .addGap(18, 18, 18)
                                .addComponent(ansDLbl0))
                            .addComponent(questionLbl0))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(questionLbl1)
                                .addGap(52, 52, 52)
                                .addGap(20, 20, 20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(answerPromptLbl1)
                                .addGap(71, 71, 71)
                                .addComponent(userAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ansALbl1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ansBLbl1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ansCLbl1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ansDLbl1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(answerPromptLbl2)
                        .addGap(18, 18, 18)
                        .addComponent(userAnswer2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ansALbl2)
                        .addGap(18, 18, 18)
                        .addComponent(ansBLbl2)
                        .addGap(18, 18, 18)
                        .addComponent(ansCLbl2)
                        .addGap(18, 18, 18)
                        .addComponent(ansDLbl2)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(questionLbl2)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(answerPromptLbl3)
                                        .addGap(71, 71, 71)
                                        .addComponent(userAnswer3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ansALbl3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ansBLbl3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ansCLbl3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ansDLbl3)
                                .addGap(12, 12, 12)
                                .addGap(34, 34, 34))
                            .addComponent(questionLbl3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(199, 199, 199)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(ansALbl4)
                                                .addGap(52, 52, 52)
                                                .addComponent(ansBLbl4)
                                                .addGap(44, 44, 44)
                                                .addComponent(ansCLbl4))
                                            .addComponent(answerPromptLbl4))
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(userAnswer4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ansDLbl4)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(questionLbl4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(numCorrectLbl)
                            .addComponent(perCorrectLbl)
                            .addComponent(numIncorrectLbl))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numCorrectNum)
                            .addComponent(perCorrectNum)
                            .addComponent(numIncorrectNum, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(questionLbl0)
                            .addComponent(questionLbl2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ansALbl0)
                            .addComponent(ansBLbl0)
                            .addComponent(ansCLbl0)
                            .addComponent(ansDLbl0))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answerPromptLbl0)
                            .addComponent(userAnswer0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ansALbl2)
                            .addComponent(ansBLbl2)
                            .addComponent(ansCLbl2)
                            .addComponent(ansDLbl2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(answerPromptLbl2)
                            .addComponent(userAnswer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(questionLbl1)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ansALbl1)
                            .addComponent(ansBLbl1)
                            .addComponent(ansCLbl1)
                            .addComponent(ansDLbl1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(answerPromptLbl1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(questionLbl3)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ansALbl3)
                                .addComponent(ansBLbl3)
                                .addComponent(ansCLbl3)
                                .addComponent(ansDLbl3))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(userAnswer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(answerPromptLbl3)))))
                .addGap(47, 47, 47)
                .addComponent(questionLbl4)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ansALbl4)
                    .addComponent(ansBLbl4)
                    .addComponent(ansCLbl4)
                    .addComponent(ansDLbl4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userAnswer4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answerPromptLbl4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numCorrectLbl)
                    .addComponent(numIncorrectNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numIncorrectLbl)
                    .addComponent(numCorrectNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(perCorrectNum)
                    .addComponent(perCorrectLbl)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userAnswer0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userAnswer0ActionPerformed
     
    }//GEN-LAST:event_userAnswer0ActionPerformed

    private void userAnswer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userAnswer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userAnswer1ActionPerformed

    private void userAnswer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userAnswer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userAnswer2ActionPerformed

    private void userAnswer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userAnswer3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userAnswer3ActionPerformed

    private void userAnswer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userAnswer4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userAnswer4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double answer0, answer1, answer2, answer3, answer4, correctScore, incorrectScore, correctPercentage;
        
                answer0 = (Double.parseDouble(userAnswer0.getText()));
                answer1 = (Double.parseDouble(userAnswer1.getText()));
                answer2 = (Double.parseDouble(userAnswer2.getText()));
                answer3 = (Double.parseDouble(userAnswer3.getText()));
                answer4 = (Double.parseDouble(userAnswer4.getText()));
                
//                if (answer0.equals "C")
//                {
//                outputMessegeLbl.setText ("you like weird sizes!");
//                }
   

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultipleChoiceQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ansALbl0;
    private javax.swing.JLabel ansALbl1;
    private javax.swing.JLabel ansALbl2;
    private javax.swing.JLabel ansALbl3;
    private javax.swing.JLabel ansALbl4;
    private javax.swing.JLabel ansBLbl0;
    private javax.swing.JLabel ansBLbl1;
    private javax.swing.JLabel ansBLbl2;
    private javax.swing.JLabel ansBLbl3;
    private javax.swing.JLabel ansBLbl4;
    private javax.swing.JLabel ansCLbl0;
    private javax.swing.JLabel ansCLbl1;
    private javax.swing.JLabel ansCLbl2;
    private javax.swing.JLabel ansCLbl3;
    private javax.swing.JLabel ansCLbl4;
    private javax.swing.JLabel ansDLbl0;
    private javax.swing.JLabel ansDLbl1;
    private javax.swing.JLabel ansDLbl2;
    private javax.swing.JLabel ansDLbl3;
    private javax.swing.JLabel ansDLbl4;
    private javax.swing.JLabel answerPromptLbl0;
    private javax.swing.JLabel answerPromptLbl1;
    private javax.swing.JLabel answerPromptLbl2;
    private javax.swing.JLabel answerPromptLbl3;
    private javax.swing.JLabel answerPromptLbl4;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel numCorrectLbl;
    private javax.swing.JLabel numCorrectNum;
    private javax.swing.JLabel numIncorrectLbl;
    private javax.swing.JLabel numIncorrectNum;
    private javax.swing.JLabel perCorrectLbl;
    private javax.swing.JLabel perCorrectNum;
    private javax.swing.JLabel questionLbl0;
    private javax.swing.JLabel questionLbl1;
    private javax.swing.JLabel questionLbl2;
    private javax.swing.JLabel questionLbl3;
    private javax.swing.JLabel questionLbl4;
    private javax.swing.JTextField userAnswer0;
    private javax.swing.JTextField userAnswer1;
    private javax.swing.JTextField userAnswer2;
    private javax.swing.JTextField userAnswer3;
    private javax.swing.JTextField userAnswer4;
    // End of variables declaration//GEN-END:variables
}
